//! `POST /handoff` — send a page as a handoff to another project.
//!
//! The panel's first write route; see
//! `docs/alfama/specs/2026-09-28-handoff-pela-tela.md` for why this route
//! exists and why it is the one place in this crate allowed to write, and
//! `crate::csrf` for the token defense every request here goes through
//! before anything else runs.
//!
//! `from_workspace`/`from_project`/`from_path` identify the page the
//! operator had open — they come from a hidden field `page.html` rendered
//! for THAT page, never from anything the operator typed. They are used for
//! exactly two things: verifying the CSRF token, and building the
//! `next_steps` back-link and the redirect target. They are NEVER used to
//! pick the destination scope or to attribute the write — a POST body that
//! names a different origin does not change whose handoff this becomes, it
//! just fails the CSRF check (the token was signed for the real origin).
//! This holds because `create_handoff` rejects a blank `to_workspace`/
//! `to_project` outright (`HandoffError::BlankDestination`) rather than
//! falling back to the origin scope for either — `ScopeResolver` otherwise
//! treats an explicit-but-blank field as "use the default", which would
//! have made `from_*` a silent influence on the destination whenever the
//! (client-side-only) `required` attribute was bypassed.

use std::sync::Arc;

use ai_memory_core::{ActorContext, ActorKey, AgentKind, NewHandoff, owner_stamp};
use ai_memory_store::{ScopeResolver, lookup_existing_scope};
use ai_memory_wiki::AdmissionOp;
use axum::Form;
use axum::extract::State;
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::{IntoResponse, Redirect, Response};
use serde::Deserialize;

use crate::csrf;
use crate::state::WebState;
use crate::templates::page_href;

/// `POST /handoff` body. Every field is a plain string — axum's `Form`
/// extractor rejects a body that isn't
/// `application/x-www-form-urlencoded`, matching the plain HTML form
/// `page.html` renders (no JS, no JSON).
#[derive(Debug, Deserialize)]
pub(crate) struct HandoffForm {
    /// Hidden field: the open page's own workspace. CSRF-bound; never used
    /// to pick a destination.
    from_workspace: String,
    /// Hidden field: the open page's own project. CSRF-bound; never used to
    /// pick a destination.
    from_project: String,
    /// Hidden field: the open page's own path. CSRF-bound; also becomes the
    /// first `next_steps` entry and the redirect target.
    from_path: String,
    /// Hidden field, generated by `crate::csrf::issue` when the page
    /// rendered. `#[serde(default)]` so a request that omits it entirely
    /// (rather than sending it empty) still reaches `csrf::verify` — which
    /// rejects the empty string exactly like any other bad token — instead
    /// of failing at form-deserialization with a generic 422 that bypasses
    /// this route's own logging and its `403` contract.
    #[serde(default)]
    csrf_token: String,
    /// Destination workspace (`<input>` free text). Created if missing.
    to_workspace: String,
    /// Destination project (`<input list>` + `<datalist>`). Created if
    /// missing.
    to_project: String,
    /// Handoff summary (textarea).
    summary: String,
    /// One next-step per line (textarea). May be blank.
    #[serde(default)]
    next_steps: String,
    /// One open question per line (textarea). May be blank.
    #[serde(default)]
    open_questions: String,
    /// Checkbox, present (any value) when checked. Checked by default in
    /// the rendered form, matching `memory_handoff_begin`'s `shared` default.
    #[serde(default)]
    shared: Option<String>,
}

impl HandoffForm {
    /// Test-only constructor for `crate::create_handoff_for_test`, which
    /// exercises scope resolution + the write path directly, bypassing the
    /// CSRF/Origin gate entirely. That is the point: the "forged from_*
    /// fields don't change the destination" guarantee has to hold on its
    /// own, independent of CSRF verification (see
    /// `docs/alfama/plans/2026-09-28-handoff-pela-tela.md` Tarefa 3 Passo 5).
    #[cfg(test)]
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn for_test(
        from_workspace: &str,
        from_project: &str,
        from_path: &str,
        to_workspace: &str,
        to_project: &str,
        summary: &str,
    ) -> Self {
        Self {
            from_workspace: from_workspace.to_owned(),
            from_project: from_project.to_owned(),
            from_path: from_path.to_owned(),
            csrf_token: String::new(),
            to_workspace: to_workspace.to_owned(),
            to_project: to_project.to_owned(),
            summary: summary.to_owned(),
            next_steps: String::new(),
            open_questions: String::new(),
            shared: Some("on".to_owned()),
        }
    }
}

/// Split a textarea's contents into non-blank, trimmed lines.
fn lines(text: &str) -> Vec<String> {
    text.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .map(str::to_owned)
        .collect()
}

/// Why `create_handoff` failed, for the redirect's `motivo=` query param
/// only — never a raw error body (spec §4.2: "nunca um corpo de erro cru").
/// `motivo()` returns one of a small fixed set of reason strings (never the
/// raw error or any caller-supplied text), so the query param cannot be used
/// to inject arbitrary content into the redirect URL.
#[derive(Debug)]
pub(crate) enum HandoffError {
    /// `to_workspace` or `to_project` was blank (after trimming). The HTML
    /// `required` attribute on both fields is client-side only — nothing
    /// stops a raw POST from omitting or blanking them — and silently
    /// falling back to the origin page's own scope would be surprising even
    /// for a legitimate caller (a destination nobody chose). Checked before
    /// scope resolution ever runs.
    BlankDestination,
    /// The requested destination could not be resolved for another reason
    /// (e.g. the origin page's own scope no longer exists).
    Resolve,
    /// The admission chain refused the operation.
    Admission,
    /// The write itself failed after everything upstream succeeded.
    Write,
}

impl HandoffError {
    pub(crate) const fn motivo(&self) -> &'static str {
        match self {
            Self::BlankDestination => "destino_vazio",
            Self::Resolve => "escopo",
            Self::Admission => "recusado",
            Self::Write => "erro",
        }
    }
}

/// `true` when `origin`'s host (scheme-stripped, up to the next `/`) matches
/// `host` exactly (case-insensitive). A malformed or unparseable `Origin`
/// counts as a mismatch — fail closed.
fn origin_matches_host(origin: &str, host: &str) -> bool {
    let without_scheme = origin.split_once("://").map_or(origin, |(_, rest)| rest);
    let origin_host = without_scheme.split('/').next().unwrap_or("");
    !origin_host.is_empty() && origin_host.eq_ignore_ascii_case(host)
}

/// Handler for `POST /handoff`.
pub(crate) async fn handler(
    State(state): State<Arc<WebState>>,
    headers: HeaderMap,
    Form(form): Form<HandoffForm>,
) -> Response {
    // 1. CSRF token, checked against the POST body's OWN from_* fields —
    // never against anything looked up separately. A forged from_workspace
    // therefore does not smuggle a token issued for a different page: the
    // token was signed for the real page's fields, so it simply fails to
    // verify against whatever the forged fields say.
    let now = csrf::now_unix_minute();
    if !csrf::verify(
        &state.csrf_key,
        &form.csrf_token,
        &form.from_workspace,
        &form.from_project,
        &form.from_path,
        now,
    ) {
        tracing::warn!("POST /handoff rejected: missing or invalid CSRF token");
        return (StatusCode::FORBIDDEN, "forbidden\n").into_response();
    }

    // 2. Origin, when the client sends one, must match this request's own
    // Host — the same same-origin posture as the Host-header allowlist
    // guard already wrapping every route, applied here against a header a
    // cross-origin page cannot spoof to *this* value (the browser sets
    // Origin itself). Absence of Origin does not fail the request on its
    // own; the token above is what actually gates the write.
    if let Some(origin) = headers.get(header::ORIGIN).and_then(|v| v.to_str().ok()) {
        let host = headers
            .get(header::HOST)
            .and_then(|v| v.to_str().ok())
            .unwrap_or_default();
        if !origin_matches_host(origin, host) {
            tracing::warn!(origin, host, "POST /handoff rejected: Origin/Host mismatch");
            return (StatusCode::FORBIDDEN, "forbidden\n").into_response();
        }
    }

    // From here on the from_* fields are trustworthy: the token could only
    // have been read off the GET response for exactly this
    // (from_workspace, from_project, from_path), which a cross-origin page
    // cannot do (CORS blocks reading the response, not sending the POST).
    let origin_href = page_href(&form.from_workspace, &form.from_project, &form.from_path);

    match create_handoff(&state, &form).await {
        Ok(()) => Redirect::to(&format!("{origin_href}?handoff=enviado")).into_response(),
        Err(err) => {
            tracing::warn!(
                motivo = err.motivo(),
                "POST /handoff did not write a handoff"
            );
            Redirect::to(&format!(
                "{origin_href}?handoff=erro&motivo={}",
                err.motivo()
            ))
            .into_response()
        }
    }
}

pub(crate) async fn create_handoff(
    state: &WebState,
    form: &HandoffForm,
) -> Result<(), HandoffError> {
    // The destination is ALWAYS resolved from to_workspace/to_project, never
    // from from_*. But `resolve_write_args` treats a blank explicit field as
    // "fall back to the default" rather than "reject" — and the HTML form's
    // `required` attribute on these two fields is a client-side nicety only,
    // not a real guard against a raw POST. Reject blank destinations
    // outright instead of silently defaulting to the origin page's own
    // scope, which would be a surprising destination for anyone — legitimate
    // caller or not — who did not actually choose it.
    if form.to_workspace.trim().is_empty() || form.to_project.trim().is_empty() {
        return Err(HandoffError::BlankDestination);
    }

    // Resolved only so `ScopeResolver` has a well-typed default to construct
    // with (its constructor requires one); with both `to_*` fields checked
    // non-blank above, `resolve_write_args` below always takes its explicit
    // `Some(..)` branch and this default is never actually used.
    let from_scope = lookup_existing_scope(&state.reader, &form.from_workspace, &form.from_project)
        .await
        .map_err(|_| HandoffError::Resolve)?;

    let actor_key = ActorKey::default();
    let to_scope = ScopeResolver::new(
        &state.reader,
        from_scope.workspace_id,
        from_scope.project_id,
    )
    .with_writer(&state.writer)
    .resolve_write_args(
        Some(form.to_workspace.trim()),
        Some(form.to_project.trim()),
        &actor_key,
    )
    .await
    .map_err(|_| HandoffError::Resolve)?;

    let admission = state
        .wiki
        .authorize_operation(
            to_scope.workspace_id,
            to_scope.project_id,
            AdmissionOp::HandoffBegin,
            ActorContext::anonymous(),
            Vec::new(),
        )
        .await
        .map_err(|_| HandoffError::Admission)?;

    let origin_note = format!(
        "Página de origem: {}",
        page_href(&form.from_workspace, &form.from_project, &form.from_path)
    );
    let mut next_steps_raw = vec![origin_note];
    next_steps_raw.extend(lines(&form.next_steps));
    let open_questions_raw = lines(&form.open_questions);

    let (summary, open_questions, next_steps, files_touched) =
        ai_memory_core::sanitize_handoff_text_fields(
            &state.sanitizer,
            &form.summary,
            &open_questions_raw,
            &next_steps_raw,
            &[],
        );

    // The web layer carries no per-request operator identity today (no
    // session actor is threaded into WebState/routes), so
    // `ActorContext::anonymous().identity_key()` is always `None` and
    // `owner_stamp` always answers `None` regardless of `shared` — see
    // `ai_memory_core::owner_identity`. Kept as an explicit call (not just
    // `None`) so the day web sessions gain a real identity, only this line
    // has to change, exactly mirroring `memory_handoff_begin`'s own
    // `shared` handling.
    let owner_user = if form.shared.is_some() {
        None
    } else {
        owner_stamp(ActorContext::anonymous().identity_key().as_ref(), false)
    };

    let handoff = NewHandoff {
        workspace_id: to_scope.workspace_id,
        project_id: to_scope.project_id,
        from_session_id: None,
        from_agent: AgentKind::Other,
        to_agent: None,
        cwd: None,
        summary,
        open_questions,
        next_steps,
        files_touched,
        owner_user,
    };

    state
        .writer
        .insert_handoff(handoff)
        .await
        .map_err(|_| HandoffError::Write)?;
    if let Some(ctx) = admission.as_ref() {
        state.wiki.notify_operation_observers(ctx);
    }
    Ok(())
}
